=== Lessrogan/rss22SB1/src/main/resources/static/resume/xml/rss22.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://univrouen.fr/rss22"
	targetNamespace="http://univrouen.fr/rss22"
	elementFormDefault="qualified" >
	<xs:element name="feed" type="feedType"/>
	
	<xs:simpleType name="restrictedString">
  		<xs:restriction base="xs:string">
   			<xs:maxLength value="128"/>
  		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="restrictedDate">
		<xs:restriction base="xs:date">
			<xs:pattern value="rfc3339"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="linkType" >
		<xs:attribute name="rel" type="relType"/>
		<xs:attribute name="url" type="urlType"/>
	</xs:complexType>
	
	<xs:simpleType name="mimeType">
		<xs:restriction base="urlType">
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="relType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="self"/>
			<xs:enumeration value="alternate"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="langType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z]{2,3}(-([A-Z]{2}|[0-9]{3}))?"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="urlType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^-_\s]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="feedType">
		<xs:sequence>
			<xs:element name="title" type="restrictedString" minOccurs="1" maxOccurs="1"/>
			<xs:element name="pubDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
			<xs:element name="copyright" type="restrictedString" minOccurs="1" maxOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="item" type="itemType" minOccurs="1" maxOccurs="10"/>
		</xs:sequence>
		<xs:attribute name="lang" type="langType"/>
	</xs:complexType>
	
	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element name="guid" type="urlType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="title" type="restrictedString" minOccurs="1" maxOccurs="1"/>
			<xs:element name="category" type="categoryType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:choice minOccurs="1" maxOccurs="1">
				<xs:element name="published" type="xs:date"/>
				<xs:element name="updated" type="xs:date"/>
			</xs:choice>
			<xs:element name="image" type="imageType" minOccurs="0" maxOccurs="1"/>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="author" type="personType"/>
				<xs:element name="contributor" type="personType"/>
			</xs:choice>
			<xs:element name="content" type="contentType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="contentType">
      <xs:simpleContent>
        <xs:extension base="xs:string">
			<xs:attribute name="src" type="xs:anyURI" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="categoryType">
		<xs:attribute name="term" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="imageType">
		<xs:attribute name="href" type="xs:anyURI"/>
		<xs:attribute name="format" type="formatType"/>
	</xs:complexType>
	
	<xs:simpleType name="formatType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GIF"/>
			<xs:enumeration value="JPEG"/>
			<xs:enumeration value="JPEG"/>
			<xs:enumeration value="BMP"/>
			<xs:enumeration value="PNG"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="personType">
		<xs:all>
			<xs:element name="name" type="personLengthRestrictionType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="email" type="mailType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="uri" type="urlType" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	
	<xs:simpleType name="personLengthRestrictionType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="64"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="mailType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^#,:;()/=~!?$*=\[\]'*&amp;]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== Lessrogan/rss22SB1/src/main/resources/static/resume/xml/rss22detailed.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:feed lang="fr" xmlns:p="http://univrouen.fr/rss22" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univrouen.fr/rss22 rss22.xsd ">
  <p:title>Feed avec details</p:title>
  <p:pubDate>11999-12-30</p:pubDate>
  <p:copyright>copyright</p:copyright>
  <p:link rel="self" url="blabla.com"/>
  <p:item>
    <p:guid>15</p:guid>
    <p:title>MySpace</p:title>
    <p:category term="Histoire"/>
    <p:published>2025-01-01</p:published>
    <p:image format="GIF" href="http://myspace.org"/>
    <p:author>
      <p:name>Barnabé Casse</p:name>
      <p:email>barnabecasse@gmail.com</p:email>
      <p:uri>barnabe.casse</p:uri>
    </p:author>
    <p:content src="http://myspace.org">C'était mon espace mais maintenant ça ne l'est plus...</p:content>
  </p:item>
  <p:item>
    <p:guid>16</p:guid>
    <p:title>Recettes d'huile de coude</p:title>
    <p:category term="Gastronomie"/>
    <p:published>2005-05-07</p:published>
    <p:image format="JPEG" href="http://coude.org"/>
    <p:author>
      <p:name>Gaspard Ccio</p:name>
      <p:email>gaspardccio@gmail.com</p:email>
      <p:uri>gaspardccio.com</p:uri>
    </p:author>
    <p:content src="http://coude.org">Ca huile</p:content>
  </p:item>
  <p:item>
    <p:guid>17</p:guid>
    <p:title>Boeuf</p:title>
    <p:category term="Langues"/>
    <p:published>2021-01-09</p:published>
    <p:image format="GIF" href="http://boeuf.org"/>
    <p:author>
      <p:name>Franck Leboeuf</p:name>
      <p:email>leboeuf@gmail.com</p:email>
      <p:uri>leboeuf.com</p:uri>
    </p:author>
    <p:content src="http://boeuf.org">Discussions, sans langue de boeuf...</p:content>
  </p:item>
</p:feed>

=== Lessrogan/rss22SB1/src/main/resources/static/resume/xml/rss22.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:feed xmlns:p="http://univrouen.fr/rss22" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univrouen.fr/rss22 rss22.xsd ">
  <p:title>RSS22 XML1</p:title>
  <p:pubDate>2001-11-28</p:pubDate>
  <p:copyright>o'top</p:copyright>
  <p:link url="http://youtube.com"/>
  <p:item>
    <p:guid>1</p:guid>
    <p:title>Les chiens sont de sortie</p:title>
    <p:category term="Documentaire"/>
    <p:published>1999-12-30</p:published>
    <p:author>
      <p:name>Denise Antoine</p:name>
    </p:author>
    <p:content>Avec l'ouverture de la chasse, les chiens sont de sortie.</p:content>
  </p:item>
  <p:item>
  	<p:guid>2</p:guid>
  	<p:title>Mon premier jour de faculté</p:title>
    <p:category term="Jeunesse"/>
  	<p:published>2001-11-28</p:published>
  	<p:author>
  		<p:name>Bertin Nicolas</p:name>
  	</p:author>
  	<p:content>Aujourd'hui est mon premier jour de faculté. Youpi !</p:content>
  </p:item>
  <p:item>
  	<p:guid>4</p:guid>
  	<p:title>En ligne de mire</p:title>
    <p:category term="Action"/>
  	<p:published>2000-01-08</p:published>
  	<p:author>
  		<p:name>Mirabelle Ervine</p:name>
  	</p:author>
  	<p:content>EN PLEIN DANS LE MILLE !</p:content>
  </p:item>
</p:feed>
